---
- name: Install Grafana
  hosts: monitoring
  become: yes
  tasks:
    - name: Install dependencies
      apt:
        name: 
          - apt-transport-https
          - software-properties-common
          - wget
        state: present

    - name: Add Grafana GPG key
      shell: "wget -q -O - https://packages.grafana.com/gpg.key | apt-key add -"

    - name: Add Grafana repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present

    - name: Install and Start Grafana
      apt:
        name: grafana
        state: latest
        update_cache: yes

    - name: Start Grafana service
      service:
        name: grafana-server
        state: started
        enabled: yes
