---
- name: Full Setup of Monitoring Server
  hosts: monitoring
  become: yes
  tasks:
    - name: Install Prometheus and Grafana
      apt:
        name: [prometheus, grafana]
        state: present
        update_cache: yes

    - name: Download Cloudflared
      get_url:
        url: https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        dest: /tmp/cloudflared.deb

    - name: Install Cloudflared package
      apt:
        deb: /tmp/cloudflared.deb

    - name: Ensure services are started
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      loop:
        - prometheus
        - grafana-server
